### ISSUE TITLE
Error - Creation of new Files 

### ISSUE THREAD

**Issue by graebec** [varungupta31/dashcam_anonymizer#4]
Hi there, after the predictions finished I receive the following error : 
![Screenshot 2023-09-08 071930 -Error ](https://github.com/varungupta31/dashcam_anonymizer/assets/38424788/ac90d727-d051-4515-980e-e46292972e75)

Any Idea what causes this ?

Best Regards

**Comment by varungupta31** [comment]
Path and file name issues.

Currently the videos would need to be named numerically `1.mp4 2.mp4`
And thus the script does an `int` call assuming the number, and sorts the videos to be processed in that order.

What is the exact path of the videos you have?

A quick fix would be to change

L45 `videos = sorted(glob.glob(f"{config['videos_path']}/*.mp4"), key=sort_videos)`
to
`videos = sorted(glob.glob(f"{config['videos_path']}/*.mp4"))`

And if the videos are not in the videos folder inside the repo,

change

L46 `videos = [int(item.split("/")[1].replace(".mp4", "")) for item in videos]`
to
`videos = [int(item.split("/")[-1].replace(".mp4", "")) for item in videos]`

I can see how this is problematic, occupied ATM, will fix things soon.

- [ ] Fix hard coded codecs to choose from the config.
- [ ] Fix relative paths.
- [ ] Fix assumption of videos names numeric.
