### ISSUE TITLE
Unable to recreate the environment.

### ISSUE THREAD

**Issue by rampallishyam** [varungupta31/dashcam_anonymizer#5]
Solving environment: failed

ResolvePackageNotFound:
  - nettle=3.6
  - libxkbcommon=1.0.1
  - dbus=1.13.18
  - gst-plugins-base=1.14.1
  - libstdcxx-ng=11.2.0
  - readline=8.2
  - nspr=4.35
  - _openmp_mutex=5.1
  - libedit=3.1.20221030
  - nss=3.89.1
  - libgcc-ng=11.2.0
  - libuuid=1.41.5
  - gnutls=3.6.13
  - ncurses=6.4
  - gmp=6.2.1
  - gstreamer=1.14.1
  - libvpx=1.7.0
  - ld_impl_linux-64=2.38
  - libgfortran5=13.1.0
  - libgfortran-ng=13.1.0
  - libgomp=11.2.0
  - openh264=2.1.1
  - x264=1!157.20191217

**Comment by varungupta31** [comment]
- Which OS are you on?
- What is the exact traceback you're getting?

**Comment by rampallishyam** [comment]
I am currently using windows 11. Please find the exact error in the image below.
![Screenshot 2023-12-05 143519](https://github.com/varungupta31/dashcam_anonymizer/assets/35885472/e8d905fc-c85a-4a83-baa4-cf3bfa208f47)

**Comment by varungupta31** [comment]
Are you using Conda?

Otherwise, you need to ensure your system is set up to manage Python and its packages. 
Other option to avoid the conda-forge packages and just install via pip all the corresponding required libraries in `environemnt.yml`.

**Comment by varungupta31** [comment]
I don't have access to a Windows machine rn.

Check out https://github.com/varungupta31/dashcam_anonymizer/issues/2#issuecomment-1676337342

Do the steps mentioned in the comment, create the environment, and install the mentioned packages manually.

See if that works.

**Comment by rampallishyam** [comment]
Tried it, still not working. I can see that torch is a dependency for ultralytics. I am creating a new environment and trying, with no luck.

**Comment by varungupta31** [comment]
What's the issue with installing torch?

https://pytorch.org/get-started/locally/ maybe of help.

If there is a package clash (or version), which is not supported on your OS atm, then there's little I could do.

**Comment by rampallishyam** [comment]
The torch issue is sorted. Now I got a new error. it says that there is `FileNotFoundError: [Errno 2] No such file or directory: 'model\\best.pt'`

**Comment by varungupta31** [comment]
Please read the repo's readme.
