### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by rampallishyam** [varungupta31/dashcam_anonymizer#6]
Traceback (most recent call last):
  File "C:\Users\rampa\Documents\LocalFiles\Learning\CV algorithm\dashcam_anonymizer\blur_videos.py", line 45, in <module>
    videos = sorted(glob.glob(f"{config['videos_path']}/*.mp4"), key=sort_videos)
  File "C:\Users\rampa\Documents\LocalFiles\Learning\CV algorithm\dashcam_anonymizer\blur_videos.py", line 43, in sort_videos
    return int(item.split("/")[1].replace(".mp4",""))
IndexError: list index out of range

**Comment by varungupta31** [comment]
Is this being followed?
`The blur_videos.py script currently expects the videos to be named numerically [1.mp4, 111.mp4]`
as in the `readme`?

**Comment by rampallishyam** [comment]
my video file name 1.mp4. Still the same error.
![image](https://github.com/varungupta31/dashcam_anonymizer/assets/35885472/67af95ac-8ee9-4ecb-a070-7b169906d0d1)

**Comment by rampallishyam** [comment]
Hi, as I was unable to debug this error, I have developed my own code and trained my own model. You can find my work here: [https://github.com/rampallishyam/PIIMask](url). Thanks for your support initially, anyway.

**Comment by varungupta31** [comment]
Got busy...Hmm. It seems like a directory structure issue.
the split 'extracts' the pat, expecting 1st index.

Glad you got something working.

**Comment by varungupta31** [comment]
Good idea to check if the config file contains the right folder path, and then some workaround for Windows mentioned in https://github.com/varungupta31/dashcam_anonymizer/issues/7
