### ISSUE TITLE
Installation in windows+conda

### ISSUE THREAD

**Issue by oipa** [varungupta31/dashcam_anonymizer#7]
I am trying to create the environment in conda but my OS is Windows 10. And I get the following error when executing `conda env create -f environment.yml`

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - gst-plugins-base=1.14.1
  - gnutls=3.6.13
  - x264=1!157.20191217
  - libuuid=1.41.5
  - libgomp=11.2.0
  - ncurses=6.4
  - libxkbcommon=1.0.1
  - gstreamer=1.14.1
  - gmp=6.2.1
  - libedit=3.1.20221030
  - nspr=4.35
  - nss=3.89.1
  - nettle=3.6
  - ld_impl_linux-64=2.38
  - libvpx=1.7.0
  - libstdcxx-ng=11.2.0
  - dbus=1.13.18
  - libgfortran-ng=13.1.0
  - openh264=2.1.1
  - libgcc-ng=11.2.0
  - _openmp_mutex=5.1
  - readline=8.2
  - libgfortran5=13.1.0

I tried deleting this packages from the environment.yml file but it still finds package conflict and does not create the environment. How can I solve this? 

Thank you!

**Comment by varungupta31** [comment]
check https://github.com/varungupta31/dashcam_anonymizer/issues/5

works?

**Comment by oipa** [comment]
Oh sorry, I didn't realize there were some issues closed related with this. So:

1) I have created a new conda environment from scratch (python==3.11), installed using pip opencv-python==4.6.0.66, pybboxes and ultralytics. 

2) When executing `python blur_videos.py --config configs/vid_blur.yaml` it also asked me for the installation of module dill which I also installed

3) This time executing `python blur_videos.py --config configs/vid_blur.yaml` again gives me the "list index out of range" error which was also reported before in #6 . But my video is already named as 1.mp4

> ERROR 
> (dashcam_anonymizer) C:\Users\-------\envs\dashcam_anonymizer>python blur_videos.py --config configs/vid_blur.yaml
> Traceback (most recent call last):
>   File "C:\Users\------------\envs\dashcam_anonymizer\blur_videos.py", line 45, in <module>
>     videos = sorted(glob.glob(f"{config['videos_path']}/*.mp4"), key=sort_videos)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\-------------\envs\dashcam_anonymizer\blur_videos.py", line 43, in sort_videos
>     return int(item.split("/")[1].replace(".mp4",""))
>                ~~~~~~~~~~~~~~~^^^
> IndexError: list index out of range

My config file `vid_blur.yaml`is

> model_path: 'model/best.pt'
> videos_path: 'videos/'
> detection_conf_thresh: 0.01
> gpu_avail: True
> vid_format: .png #or any other format supported by YOLO
> vid_width: 960
> vid_height: 540
> generate_detections: False #False if the YOLO annotations already present (saves compute!)
> generate_jsons: True
> vid_fps: 60
> blur_radius: 31 #increase to increase blur intensity (odd values)
> output_folder: blurred_videos/

and if I print the `glob.glob(f"{config['videos_path']}/*.mp4"))` I got `['videos\\1.mp4', 'videos\\111.mp4']`

**Comment by varungupta31** [comment]
I see. Can you try
changing
```
def sort_videos(item):
    return int(item.split("/")[1].replace(".mp4",""))

videos = sorted(glob.glob(f"{config['videos_path']}/*.mp4"), key=sort_videos)
videos = [int(item.split("/")[1].replace(".mp4", "")) for item in videos]
```

to

```
def sort_videos(item):
    return int(item.split("\\")[1].replace(".mp4",""))

videos = sorted(glob.glob(f"{config['videos_path']}/*.mp4"), key=sort_videos)
videos = [int(item.split("\\")[1].replace(".mp4", "")) for item in videos]
```

this might work, due to how paths are different in linux vs windows. linux does `this/is/my/path`, and windows does `this\is\my\path` or `this\\is\\my\\path`

So, either `\` or `\\` replacement should work.

I dont have a windows machine rn, tough to exactly recreate, but if this doesn't solve then lmk.

**Comment by oipa** [comment]
Thank you for your response @varungupta31!

Indeed that was the problem. I also replaced `split("/")` by `split("\\")` in lines 100, 109 and 135. And now it works :)

**Comment by varungupta31** [comment]
Cool. I believe this would have been avoided had I used `Pathlib`, wasn't aware at the time I made this. Should be a simple add on, i'll see.
