### ISSUE TITLE
Dataset sharing

### ISSUE THREAD

**Issue by NhatAnh1708** [varungupta31/dashcam_anonymizer#8]
If you can share the dataset for training, i'm so happy about it. I want to try with yolov9 and other model version of OD.
thank for reading

**Comment by varungupta31** [comment]
Hey @NhatAnh1708, thanks for your interest in this.
Nope, I don't have the training data with me anymore.

You can follow a similar pipeline as I did, which is getting the license plates and faces data from OpenImagesDataset. Shouldn't be too much effort, and maybe they added more photos for these categories now!

I'd be happy to mention/include any model you train on these classes in this repo, good luck!

**Comment by NhatAnh1708** [comment]
Thanks a lot
