### ISSUE TITLE
I want to output a video with the vehicle number plates and person faces blurred. However, an error occurs when I try to do this

### ISSUE THREAD

**Issue by divya70063** [varungupta31/dashcam_anonymizer#9]
Speed: 4.3ms preprocess, 441.3ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 1088)
Results saved to runs/detect/yolo_videos_pred7
337 labels saved to runs/detect/yolo_videos_pred7/labels
Traceback (most recent call last):
  File "blur_videos.py", line 45, in <module>
    videos = sorted(glob.glob(f"{config['videos_path']}/*.mp4"), key=sort_videos)
  File "blur_videos.py", line 43, in sort_videos
    return int(item.split("/")[1].replace(".mp4",""))
ValueError: invalid literal for int() with base 10: 'media'

**Comment by varungupta31** [comment]
Please follow the instructions described in the `README`.

```
The blur_videos.py script currently expects the videos to be named numerically [1.mp4, 111.mp4]
```

It seems that your file name is non-numeric.

**Comment by varungupta31** [comment]
Feel free to re-open in case of issues.

**Comment by divya70063** [comment]
Hi

Regarding error will showing my laptop windows and python code using please provide code and iam  changing code line detecting only Indian vehicle I want all country vehicles as well as face also not  blurring.

**Comment by varungupta31** [comment]
> Regarding error will showing my laptop windows and python code using please provide code and iam  changing code line detecting only Indian vehicle I want all country vehicles as well as face also not  blurring.

Uhm, I don't think I understand your concern. Can you please be more legible?

- Windows: Yes, the code works with Windows, but you would benefit from a GPU.
- Only Indian Vehicles: No such constraint exists on the license plates. I believe that if the image contains a vehicle with a license plate (basically a rectangle with some text), then enough context prevails for the model to detect it. So, it should technically blur _all country vehicles_, as long as it looks pretty similar to the Indian plates.
- Not all faces blurred: Yes, this may happen. Faces are more tricky objects. Racial biases in datasets also don't help. So, yes, the quality of license plate detection is >> the quality of face detection in this work. Feel free to improve the models with more variety and representation in the data.

**Comment by divya70063** [comment]
Hi Varun,

I want weight file(onnx), like other country  numberplates n faces not blurred,I search n some image trained but not performing please any help n suggestion for me .
